version: '3.7'

services:
  nginx:
    image: germanzero/nginx
    volumes:
      - /var/apps/civicrm/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/apps/civicrm/drupal:/var/www/html/
    networks:
      - civicrm
      - bastion
    deploy:
      placement:
        constraints:
          - node.labels.name == germanzero-2
  
  php:
    image: germanzero/civicrm
    volumes:
      - /var/apps/civicrm/drupal:/var/www/html/
      - /var/apps/civicrm/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - civicrm
    deploy:
      placement:
        constraints:
          - node.labels.name == germanzero-2

  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - /var/apps/civicrm/mysql:/var/lib/mysql
    networks:
      - civicrm
    deploy:
      placement:
        constraints:
          - node.labels.name == germanzero-2

  api:
    image: germanzero/api:staging
    environment:
      - NODE_ENV=production
      - BASEURL=https://germanzero.org
      - LOGLEVEL=debug
    volumes:
      - /var/apps/civicrm/api:/app/store
    networks:
      - bastion

networks:
  civicrm:
  bastion:
    external: true
